### ISSUE TITLE
Map type changed => Compile error

### ISSUE THREAD

**Issue by mmaurus** [sempr-tk/sempr-orogen#1]
Hi,

due to the changes in sempr/query/SPARQLQuery.hpp (sempr-tk/sempr@6cdba966bc64fa5606e6a95200d4e0ca57c50aba ) the type of results does not correspond to function header in sempr-tk/semp-rock/src/ObjectMessages.hpp
So this rock task does not compile at SEMPREnvironment.cpp:232

**Comment by niniemann** [comment]
fixed in 6dd231f24831f9c42de518f123fde42104e01f7f
